import type { CmsConfig } from "decap-cms-core";

export const cmsConfig: CmsConfig = {
  local_backend: true,
  backend: {
    name: "git-gateway",
    branch: "decapcms",
  },
  display_url: "http://localhost:4321",
  media_folder: "src/images",
  public_folder: "/src/images",
  collections: [
    // Blog Posts
    {
      name: "posts",
      label: "Blog Posts",
      label_singular: "Blog Post",
      folder: "src/content/blog",
      create: true,
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}",
      extension: "md",
      format: "frontmatter",
      fields: [
        {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
        },
        {
          label: "Slug",
          name: "slug",
          widget: "string",
          required: true,
        },
        {
          label: "Date",
          name: "date",
          widget: "datetime",
          required: true,
        },
        {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        },
        {
          label: "Featured Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          required: false,
        },
        {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "tags",
          search_fields: ["title", "slug"],
          value_field: "slug",
          display_fields: ["title"],
          multiple: true,
        },
        {
          label: "Body",
          name: "body",
          widget: "markdown",
          required: true,
        },
      ],
    },
    // Tags
    {
      name: "tags",
      label: "Tags",
      folder: "src/content/tags",
      create: true,
      slug: "{{slug}}",
      label_singular: "Tag",
      description: "Tags for blog posts",
      format: "json",
      editor: {
        preview: false,
      },
      fields: [
        {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
        },
        {
          label: "Slug",
          name: "slug",
          widget: "string",
          required: true,
        },
        {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        },
        {
          label: "Color",
          name: "color",
          widget: "color",
          default: "#000000",
          required: true,
        },
      ],
    },
    // Projects
    {
      name: "projects",
      label: "Projects",
      folder: "src/content/projects",
      create: true,
      slug: "{{slug}}",
      label_singular: "Project",
      description: "Projects for the portfolio",
      format: "frontmatter",
      editor: {
        preview: false,
      },
      fields: [
        {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
        },
        {
          label: "Slug",
          name: "slug",
          widget: "string",
          required: true,
        },
        {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        },
        {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "tags",
          search_fields: ["title", "slug"],
          value_field: "slug",
          display_fields: ["title"],
          multiple: true,
        },
        {
          label: "Featured Image",
          name: "featuredImage",
          hint: "This will be the image that appears on the project page",
          widget: "image",
          required: false,
          allow_multiple: false,
        },
        {
          label: "Link",
          name: "link",
          widget: "string",
          required: false,
        },
        {
          label: "Body",
          name: "body",
          widget: "markdown",
          required: false,
        },
        {
          label: "Completed On",
          name: "completedOn",
          widget: "datetime",
          required: false,
        },
        {
          label: "Is Active",
          name: "isActive",
          widget: "boolean",
          default: true,
        },
        {
          label: "Pinned",
          name: "pinned",
          widget: "boolean",
          default: false,
          required: false,
        },
        {
          label: "Experience",
          name: "experience",
          widget: "string",
          required: false,
        },
      ],
    },
    // Experience
    {
      name: "experience",
      label: "Experience",
      folder: "src/content/experience",
      create: true,
      slug: "{{slug}}",
      label_singular: "Experience",
      description: "Experience for the portfolio",
      format: "json",
      editor: {
        preview: false,
      },
      fields: [
        {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
        },
        {
          label: "Slug",
          name: "slug",
          widget: "string",
          required: true,
        },
        {
          label: "Location",
          name: "location",
          widget: "string",
          required: true,
        },
        {
          label: "Date",
          name: "date",
          widget: "datetime",
          required: true,
        },
        {
          label: "End Date",
          name: "endDate",
          widget: "datetime",
          required: false,
          date_format: "YYYY-MM",
        },
        {
          label: "Role",
          name: "role",
          widget: "string",
          required: true,
        },
        {
          label: "Responsibilities",
          name: "responsibilities",
          widget: "list",
          required: true,
        },
        {
          label: "Skills",
          name: "skills",
          widget: "list",
          required: true,
        },
        {
          label: "Tools",
          name: "tools",
          widget: "list",
          required: true,
        },
        {
          label: "Projects",
          name: "projects",
          widget: "relation",
          collection: "projects",
          search_fields: ["title", "slug"],
          value_field: "slug",
          display_fields: ["title"],
          multiple: true,
          required: false,
        },
        {
          label: "Achievements",
          name: "achievements",
          widget: "list",
          required: true,
        },
        {
          label: "Is Active",
          name: "isActive",
          widget: "boolean",
          default: true,
        },
      ],
    },
  ],
};
